language: rust
rust:
  - stable
cache: cargo

services:
  - docker

env:
  global:
    - DOCKER_USER="bpteodor"
    - CONTAINER_NAME="$DOCKER_USER/flipid"

jobs:
  include:
    - stage: compile
      script: cargo build
    - stage: test
      script: cargo test
    - stage: dockerize
      script:
        - PRJ_VERSION=$(grep -E '^\s*version\s*=\s*"*"' Cargo.toml | cut -f2 -d \");
          if [ "${TRAVIS_BRANCH}" == "master" ]; then
          VERSION="$PRJ_VERSION.$TRAVIS_BUILD_NUMBER";
          else
          VERSION=$PRJ_VERSION-SNAMPSHOT;
          fi
        - IMG_ID=$(docker build . -q -t $CONTAINER_NAME)
        - docker tag $IMG_ID $CONTAINER_NAME:$VERSION
        - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
        - docker push $CONTAINER_NAME

stages:
  - compile
  - test
  - dockerize
#  - name: deploy
#    if: branch = master
