language: rust
rust:
  - stable
cache: cargo

jobs:
  include:
    - stage: Compile
      script: cargo build
    - stage: Test
      script: cargo test

stages:
  - compile
  - test
#  - name: deploy
#    if: branch = master
