language: minimal

services:
  - docker

#cache: cargo
cache:
  directories:
  - $TRAVIS_BUILD_DIR/target
  - $HOME/.cargo

env:
  global:
    - DOCKER_USER="bpteodor"
    - CONTAINER_NAME="$DOCKER_USER/flipid"
    - CARGO_ARGS="--rm -ti -v $TRAVIS_BUILD_DIR:/work -v $HOME/.cargo/repository:/usr/local/cargo/repository -w /work"

jobs:
  include:
    - stage: compile
      before_install:
        - docker pull rust
      script: 
        - docker run $CARGO_ARGS rust cargo build
        - docker run $CARGO_ARGS rust cargo test
    - stage: dockerize
      script:
        - PRJ_VERSION=$(grep -E '^\s*version\s*=\s*"*"' Cargo.toml | cut -f2 -d \");
          if [ "${TRAVIS_BRANCH}" == "master" ]; then
          VERSION="$PRJ_VERSION.$TRAVIS_BUILD_NUMBER";
          else
          VERSION=$PRJ_VERSION-SNAMPSHOT;
          fi
        - IMG_ID=$(docker build . -q -t $CONTAINER_NAME)
        - docker tag $IMG_ID $CONTAINER_NAME:$VERSION
        - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USER --password-stdin
        - docker push $CONTAINER_NAME

stages:
  - compile
  - dockerize
#  - name: deploy
#    if: branch = master
