language: rust
rust:
  - stable
cache: cargo

services:
  - docker

jobs:
  include:
    - stage: compile
      script: cargo build
    - stage: test
      script: cargo test
    - stage: dockerize
      script: docker build . -t bpteodor/flipid && echo "$DOCKER_PASSWORD" | docker login -u bpteodor --password-stdin && docker push bpteodor/flipid

stages:
  - compile
  - test
  - dockerize
#  - name: deploy
#    if: branch = master
