language: rust
rust:
  - stable
cache: cargo

services:
  - docker

jobs:
  include:
    - stage: compile
      script: docker run --rm -ti -v $(pwd):/work -v $TRAVIS_BUILD_DIR/target:/work/target -v $HOME/.cargo/:/usr/local/cargo -w /work rust cargo build
    - stage: test
      script: docker run --rm -ti -v $(pwd):/work -v $TRAVIS_BUILD_DIR/target:/work/target -v $HOME/.cargo/:/usr/local/cargo -w /work rust cargo test
    - stage: dockerize and push
      script: docker build . -t bpteodor/flipid && echo "$DOCKER_PASSWORD" | docker login -u bpteodor --password-stdin && docker push bpteodor/flipid

stages:
  - compile
  - test
  - dockerize
#  - name: deploy
#    if: branch = master
