# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  imageName: "bpteodor/flipid"
  dockerHub: "DockerHub"

stages:
  - stage: Build
    displayName: Build & push image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - bash: |
              PRJ_VERSION=$(grep -E '^\s*version\s*=\s*"*"' Cargo.toml | cut -f2 -d \")
              VERSION=$PRJ_VERSION.$BUILD_NO-$BRANCH_NAME
              if [ "${BRANCH_NAME}" == "master" ]; then
                VERSION="$PRJ_VERSION.$BUILD_NO"
              fi
              echo "##vso[task.setvariable variable=BUILD_VERSION]$VERSION"
              echo "BUILD_VERSION: $VERSION"
            env:
              BUILD_NO: $(Build.BuildId)
              BRANCH_NAME: $(Build.SourceBranchName)
          - task: Docker@2
            displayName: Build an image
            inputs:
              command: build
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              repository: $(imageName)
              tags: |
                $(BUILD_VERSION)
                latest
          - task: Docker@2
            displayName: Push image
            inputs:
              containerRegistry: |
                $(dockerHub)
              repository: $(imageName)
              command: push
              tags: |
                $(BUILD_VERSION)
                latest
